### PR TITLE
[W-11762623] reverting munit.extensions.maven.plugin.version

### PR DESCRIPTION
**Pull request by cristianchan-mulesoft**
!gate waiver add Sonar

### CODE REVIEW

**Review by GuidoGianfrate — APPROVED** [review]

**Review by acurci-at-mulesoft — APPROVED** [review]

**Comment by jbianco** [comment]
!gate waiver add Sonar

**Comment by cristianchan-mulesoft** [comment]
!gate waiver add Sonar

**Comment by jonas19** [comment]
!gate waiver add Sonar

**Comment by acurci-at-mulesoft** [comment]
!gate waiver add Sonar

**Comment by anosenzo** [comment]
!gate waiver add Sonar

**Comment by facunlk** [comment]
!gate waiver add Sonar

**Pull request merged**
